name: Build using vcpkg

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}
    name: "${{ github.workflow }}: ${{ matrix.os }}"

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      sgl_REPO_DIR: ${{ github.workspace }}/sgl-repo
      sgl_DIR: ${{ github.workspace }}/sgl

    steps:
    - uses: actions/checkout@v2

    - uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '2a6371b01420d8820d158b4707e79931feba27aa'

    - name: Output
      if: always()
      shell: bash
      run: |
        cat /home/runner/work/ActionsTestRepo3/ActionsTestRepo3/vcpkg/buildtrees/shaderc/config-x64-linux-dbg-CMakeCache.txt.log
        cat /home/runner/work/ActionsTestRepo3/ActionsTestRepo3/vcpkg/buildtrees/shaderc/config-x64-linux-rel-CMakeCache.txt.log
        cat /home/runner/work/ActionsTestRepo3/ActionsTestRepo3/vcpkg/buildtrees/shaderc/config-x64-linux-out.log
        cat /home/runner/work/ActionsTestRepo3/ActionsTestRepo3/build/vcpkg_installed/vcpkg/issue_body.md

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B "${{github.workspace}}/build" -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
